### ISSUE TITLE
Compiled sitemap.xml failed, Please check your homepage

### ISSUE THREAD

**Issue by JohnApache** [mortalYoung/umi-plugin-sitemap#4]
翻了一下示例代码，是需要我配置 `package.json` 添加一个 `homepage` 字段，这个文档并没有标注出来 看了示例才知道的。  
我觉得放到 `package.json`里并不是很灵活，为什么不直接放到 `.umirc.ts` 配置里呢?   还有能否支持配置数组生成多个域名下的 `sitemap.xml`,   假设有部署多个域名的场景 的话。。。

**Comment by mortalYoung** [comment]
我考虑到大部分有 `sitemap.xml` 需求的项目都会设置 `homepage` 的情况，所以直接取 `homepage` 并且忘记在文档中说明了。

我已经在刚 `publish` 的版本中添加了 `homepage` 的参数，并且在 `README` 中新增了两种 `examples`。我觉得你说的有道理。

你的第二个需求我不是很明白，是一个 `sitemap.xml` 文件会让多个域名使用吗？

**Comment by JohnApache** [comment]
@mortalYoung  可能是我第二个需求场景比较特殊吧。 因为我想要一份代码部署到多个域名上，所以我想着能否写到配置里，然后支持数组生成多个 域名下的 `sitemap.xml`,
